# Generated by Django 4.0.8 on 2023-08-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='series',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='series',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
